# Generated by Django 4.2.8 on 2024-02-09 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="categories",
            table="category",
        ),
    ]
