# Generated by Django 4.2.8 on 2024-02-14 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="products",
            options={
                "ordering": ["id"],
                "verbose_name": "product",
                "verbose_name_plural": "products",
            },
        ),
    ]
